server:
  port: 9772

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: OCR-SERVICE
          uri: https://classique-saucisson-85233.herokuapp.com
          predicates: Path=/api/v2/ocr/**
        - id: TRANSLATE-SERVICE
          uri: https://baroque-chaise-29236.herokuapp.com
          predicates:
            - Path=/api/v2/translate
